# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

spring:
  servlet:
    #设置单个文件的大小
    multipart:
      max-request-size: 50MB
      #设置单次请求的文件的总大小
      max-file-size: 200MB

  datasource:
    url: jdbc:mysql://localhost:3306/ysld_test?serverTimezone=UTC&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.el: debug

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.el.model
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

knife4j:
  enable: true
  setting:
    # 是否开启调试功能  true开启  false关闭
    enableDebug: true





